### ISSUE TITLE
welcome back.

### ISSUE THREAD

**Issue by Awannaphasch2016** [semiosis/pen.el#1]
Welcome back my brother, I thought you were gone forever.

**Comment by mullikine** [comment]
If I remain I will be building my house (my life) 'on the rock' this time with much better foundations, which is praticing Jesus' commands in truth and reality. I have an analogy of a person to a rocket: The 10 commandments (God's law) is like the trajectory/alignment of the heart. And some of Jesus' commands found in Luke chapter 6 are about virtue, which is like the propellant; Love your enemies, do not judge, be merciful etc. And there is no more self-righteousness in me. Salvation comes through faith in Jesus and His resurrection, and faith in partaking in it. I don't know how it all works (life, the universe and everthing) but going forward, my life, including this project will have a stronger focus on meditation of Jesus' commands and the Great Commission (that is, spreading of the gospel of Jesus and the message of His kingdom). I'd like to, for example, build into emacs some graphs / note-taking tools for meditating on and applying Jesus' commands to my life or the life of the user. I copied some out.

### John 14:15
Jesus said, "If ye love me, keep my commandments" 

### Matthew 4:17, Repent
"From that time Jesus began to preach, and to say, Repent: for the kingdom of heaven is at hand" 

### Matthew 4:19, Follow Me
"And he saith unto them, Follow me, and I will make you fishers of men" 

### Matthew 5:11-12, Rejoice
"Blessed are ye, when men shall revile you, and persecute you, and shall say all manner of evil against you falsely, for my sake. Rejoice, and be exceeding glad: for great is your reward in heaven: for so persecuted they the prophets which were before you" 

### Matthew 5:16, Let Your Light Shine
"Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven" 

### Matthew 5:17, Honor God's Law
"Think not that I am come to destroy the law, or the prophets: I am not come to destroy, but to fulfill" 

### Matthew 5:23-25, Be Reconciled
"Therefore if thou bring thy gift to the altar, and there rememberest that thy brother hath aught against thee; leave there thy gift before the altar, and go thy way; first be reconciled to thy brother, and then come and offer thy gift" 

### Matthew 5:28-30, Do Not Lust
"But I say unto you, That whosoever looketh on a woman to lust after her hath committed adultery with her already in his heart. And if thy right eye offend thee, pluck it out, and cast it from thee: for it is profitable for thee that one of thy members should perish, and not that thy whole body should be cast into hell. And if thy right hand offend thee, cut it off, and cast it from thee: for it is profitable for thee that one of thy members should perish, and not that thy whole body should be cast into hell" 

### Matthew 5:37, Keep Your Word
"Let your communication be, Yea, yea; Nay, nay: for whatsoever is more than these cometh of evil" 

### Matthew 5:38-42, Go the Second Mile
"Ye have heard that it hath been said, An eye for an eye, and a tooth for a tooth: but I say unto you, That ye resist not evil: but whosoever shall smite thee on thy right cheek, turn to him the other also. And if any man will sue thee at the law, and take away thy coat, let him have thy cloak also. And whosoever shall compel thee to go a mile, go with him twain. Give to him that asketh thee, and from him that would borrow of thee turn not thou away" 

### Matthew 5:44-46, Love Your Enemies
"But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you; that ye may be the children of your Father which is in heaven: for he maketh his sun to rise on the evil and on the good, and sendeth rain on the just and on the unjust. For if ye love them which love you, what reward have ye? Do not even the publicans the same?" 

### Matthew 5:46-48, Be Perfect
"If ye love them which love you, what reward have ye? do not even the publicans the same? And if ye salute your brethren only, what do ye more than others? do not even the publicans so? Be ye therefore perfect, even as your Father which is in heaven is perfect" 

### Matthew 6:1-18, Practice Secret Disciplines
"... When thou doest thine alms, let not thy left hand know what thy right hand doeth: that thine alms may be in secret: and thy Father which seeth in secret himself shall reward thee openly.... When thou prayest, enter into thy closet, and when thou hast shut thy door, pray to thy Father which is in secret; and thy Father which seeth in secret shall reward thee openly.... When thou fastest, anoint thine head, and wash thy face; that thou appear not unto men to fast, but unto thy Father which is in secret: and thy Father, which seeth in secret, shall reward thee openly" 

### Matthew 6:19-21, Lay Up Treasures in Heaven
"Lay not up for yourselves treasures upon earth, where moth and rust doth corrupt, and where thieves break through and steal: but lay up for yourselves treasures in heaven, where neither moth nor rust doth corrupt, and where thieves do not break through nor steal: for where your treasure is, there will your heart be also" 

### Matthew 6:33, Seek God's Kingdom
"Seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you" 

### Matthew 7:1-3, Judge Not
"Judge not, that ye be not judged. For with what judgment ye judge, ye shall be judged: and with what measure ye mete, it shall be measured to you again. And why beholdest thou the mote that is in thy brother's eye, but considerest not the beam that is in thine own eye?" 

### Matthew 7:6, Do Not Cast Pearls
"Give not that which is holy unto the dogs, neither cast ye your pearls before swine, lest they trample them under their feet, and turn again and rend you" 

### Matthew 7:7-8, Ask, Seek, Knock
"Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you: for every one that asketh receiveth; and he that seeketh findeth; and to him that knocketh it shall be opened" 

### Matthew 7:12, Do Unto Others
"Therefore all things whatsoever ye would that men should do to you, do ye even so to them: for this is the law and the prophets" 

### Matthew 7:13-14, Choose the Narrow Way
"Enter ye in at the strait gate: for wide is the gate, and broad is the way, that leadeth to destruction, and many there be which go in thereat: because strait is the gate, and narrow is the way, which leadeth unto life, and few there be that find it" 

### Matthew 7:15-16, Beware of False Prophets
"Beware of false prophets, which come to you in sheep's clothing, but inwardly they are ravening wolves. Ye shall know them by their fruits. Do men gather grapes of thorns, or figs of thistles?" 

### Matthew 9:37-38, Pray for Laborers
"The harvest truly is plenteous, but the laborers are few; pray ye therefore the Lord of the harvest, that he will send forth laborers into his harvest" 

### Matthew 10:16, Be Wise as Serpents
"Behold, I send you forth as sheep in the midst of wolves: be ye therefore wise as serpents, and harmless as doves" 

### Matthew 10:28, Fear Not
"Fear not them which kill the body, but are not able to kill the soul: but rather fear him which is able to destroy both soul and body in hell" 

### Matthew 11:15, Hear God's Voice
"He that hath ears to hear, let him hear" 

### Matthew 11:28-30, Take My Yoke
"Come unto me, all ye that labor and are heavy laden, and I will give you rest. Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls. For my yoke is easy, and my burden is light" 

### Matthew 15:4, Honor Your Parents
"For God commanded, saying, Honor thy father and mother: and, he that curseth father or mother, let him die the death" 

### Matthew 16:6, Beware of Leaven
"Take heed and beware of the leaven of the Pharisees and of the Sadducees" 

### Luke 9:23-25, Deny Yourself
"If any man will come after me, let him deny himself, and take up his cross daily, and follow me. For whosoever will save his life shall lose it: but whosoever will lose his life for my sake, the same shall save it. For what is a man advantaged, if he gain the whole world, and lose himself, or be cast away?" 

### Matthew 18:10, Despise Not Little Ones
"Take heed that ye despise not one of these little ones; for I say unto you, That in heaven their angels do always behold the face of my Father which is in heaven" 

### Matthew 18:15-17, Go to Offenders
"Moreover if thy brother shall trespass against thee, go and tell him his fault between thee and him alone: if he shall hear thee, thou hast gained thy brother. But if he will not hear thee, then take with thee one or two more, that in the mouth of two or three witnesses every word may be established. And if he neglect to hear them, tell it unto the church: but if he neglect to hear the church, let him be unto thee as a heathen man and a publican" 

### Luke 12:15, Beware of Covetousness
"And he said unto them, Take heed, and beware of covetousness: for a man's life consisteth not in the abundance of the things which he possesseth" 

### Matthew 18:21-22, Forgive Offenders
"Then came Peter to him, and said, Lord, how oft shall my brother sin against me, and I forgive him? till seven times? Jesus saith unto him, I say not unto thee, Until seven times: but, Until seventy times seven" 

### Matthew 19:4-6, Honor Marriage
"And he answered and said unto them, Have ye not read, that he which made them at the beginning made them male and female, and said, For this cause shall a man leave father and mother, and shall cleave to his wife: and they twain shall be one flesh? Wherefore they are no more twain, but one flesh. What therefore God hath joined together, let not man put asunder" 

### Matthew 20:26-28, Be a Servant
"... Whosoever will be great among you, let him be your minister; and whosoever will be chief among you, let him be your servant: even as the Son of man came not to be ministered unto, but to minister, and to give his life a ransom for many" 

### Matthew 21:13, Be a House of Prayer
"It is written, My house shall be called the house of prayer... " 

### Matthew 21:21-22, Ask in Faith
"Verily I say unto you, If ye have faith, and doubt not, ye shall not only do this which is done to the fig tree, but also if ye shall say unto this mountain, Be thou removed, and be thou cast into the sea: it shall be done. And all things, whatsoever ye shall ask in prayer, believing, ye shall receive" 

### Luke 14:12-14, Bring In the Poor
"Then said he also to him that bade him, When thou makest a dinner or a supper, call not thy friends, nor thy brethren, neither thy kinsmen, nor thy rich neighbors; lest they also bid thee again, and a recompense be made thee. But when thou makest a feast, call the poor, the maimed, the lame, the blind: and thou shalt be blessed; for they cannot recompense thee: for thou shalt be recompensed at the resurrection of the just" 

### Matthew 22:19-21, Render to Caesar
"Show me the tribute money. And they brought unto him a penny. And he saith unto them, Whose is this image and superscription? They say unto him, Caesar's. Then saith he unto them, Render therefore unto Caesar the things which are Caesar's; and unto God the things that are God's" 

### Matthew 22:37-38, Love the Lord
"Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind. This is the first and great commandment" 

### Matthew 22:39-40, Love Your Neighbor
"And the second [commandment] is like unto it, Thou shalt love thy neighbor as thyself. On these two commandments hang all the law and the prophets" 

### Matthew 24:42-44, Await My Return
"Watch therefore: for ye know not what hour your Lord doth come. But know this, that if the goodman of the house had known in what watch the thief would come, he would have watched, and would not have suffered his house to be broken up. Therefore be ye also ready: for in such an hour as ye think not the Son of man cometh" 

### Matthew 26:26-28, Take, Eat, and Drink
"As they were eating, Jesus took bread, and blessed it, and broke it, and gave it to the disciples, and said, Take, eat; this is my body. And he took the cup, and gave thanks, and gave it to them, saying, Drink ye all of it; for this is my blood of the new testament, which is shed for many for the remission of sins" 

### John 3:5-7, Be Born Again
"Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God. That which is born of the flesh is flesh; and that which is born of the Spirit is spirit. Marvel not that I said unto thee, Ye must be born again" 

### John 14:15, Keep My Commandments
"If ye love me, keep my commandments" 

### Matthew 26:41, Watch and Pray
"Watch and pray, that ye enter not into temptation: the spirit indeed is willing, but the flesh is weak" 

### John 21:15-16, Feed My Sheep
"So when they had dined, Jesus saith to Simon Peter, Simon, son of Jona, lovest thou me more than these? He saith unto him, Yea, Lord; thou knowest that I love thee. He saith unto him, Feed my lambs. He saith to him again the second time, Simon, son of Jona, lovest thou me? He saith unto him, Yea, Lord; thou knowest that I love thee. He saith unto him, Feed my sheep" 

### Matthew 28:19, Baptize My Disciples
"Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost" 

### Luke 24:49, Receive God's Power
"And, behold, I send the promise of my Father upon you: but tarry ye in the city of Jerusalem, until ye be endued with power from on high" 

### Matthew 28:19-20, Make Disciples
"Go ye therefore, and teach all nations... teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you always, even unto the end of the world. Amen" 

### Luke 6:46-49
`46 "Why do you call me, 'Lord, Lord,' and do not do what I say? 47 As for everyone who comes to me and hears my words and puts them into practice, I will show you what they are like. 48 They are like a man building a house, who dug down deep and laid the foundation on rock. When a flood came, the torrent struck that house but could not shake it, because it was well built. 49 But the one who hears my words and does not put them into practice is like a man who built a house on the ground without a foundation. The moment the torrent struck that house, it collapsed and its destruction was complete."`

### 1 Thessalonians 5:4-9
`But you, brethren, are not in darkness, that the day would overtake you like a thief; for you are all sons of light and sons of day. We are not of night nor of darkness; so then let us not sleep as others do, but let us be alert and sober.

### 1 Thessalonians 1:9-10
`$DUMP/tmp/scratchTGsY8c.txtFor they themselves report about us what kind of a reception we had with you, and how you turned to God from idols to serve a living and true God, and to wait for His Son from heaven, whom He raised from the dead, that is Jesus, who rescues us from the wrath to come.`

**Comment by Awannaphasch2016** [comment]
What is the best way to get in touch with you? I really wanna catch up. reach out to me on Twitter at least.
